import type { Consumable } from "@/lib/types";

export const consumables: Consumable[] = [
  {
    name: "칫솔",
    category: "욕실",
    cycle: "2~3개월",
    days: 90,
    reason: "칫솔모가 닳으면 세정력이 떨어지고 위생 관리가 어려워질 수 있어요.",
    replaceSigns: ["칫솔모가 벌어졌을 때", "변색되었을 때", "감기 후 다시 사용할 때"],
    tips: ["사용 후 물기를 충분히 털어 말리기", "통풍이 잘 되는 곳에 보관하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "칫솔모와 손잡이를 분리하기 어렵다면 일반쓰레기로 버려주세요.",
  },
  {
    name: "치실",
    category: "욕실",
    cycle: "1~2개월",
    days: 45,
    reason: "보관 상태가 좋지 않으면 위생적으로 사용하기 어려울 수 있어요.",
    replaceSigns: ["케이스가 오염되었을 때", "실이 끊기기 쉬울 때", "냄새가 날 때"],
    tips: ["물기 적은 곳에 보관하기", "케이스 외부도 함께 청소하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "사용한 치실과 케이스는 보통 일반쓰레기로 버려주세요.",
  },
  {
    name: "면도날",
    category: "욕실",
    cycle: "2~4주",
    days: 21,
    reason: "날이 무뎌지면 피부 자극과 상처 위험이 커질 수 있어요.",
    replaceSigns: ["면도가 잘 안 될 때", "피부가 따갑거나 자극될 때", "날에 녹이 보일 때"],
    tips: ["사용 후 물기를 제거하기", "습기 적은 곳에 보관하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "신문지나 종이에 감싸 일반쓰레기로 버려주세요.",
  },
  {
    name: "렌즈 케이스",
    category: "욕실",
    cycle: "1~3개월",
    days: 60,
    reason: "렌즈 케이스는 눈 건강과 직접 관련돼 위생 관리가 중요해요.",
    replaceSigns: ["안쪽에 이물질이 남을 때", "변색되었을 때", "스크래치가 많아졌을 때"],
    tips: ["렌즈 용액으로 헹군 뒤 건조하기", "물로만 세척하지 않기"],
    disposalType: "일반쓰레기",
    disposalGuide: "작고 오염된 플라스틱은 보통 일반쓰레기로 버려주세요.",
  },
  {
    name: "샤워기 필터",
    category: "욕실",
    cycle: "2~3개월",
    days: 90,
    reason: "필터가 오염되면 물 상태와 수압에 영향을 줄 수 있어요.",
    replaceSigns: ["필터 색이 눈에 띄게 변했을 때", "수압이 약해졌을 때", "이물질이 보일 때"],
    tips: ["사용 환경에 따라 더 빨리 교체하기", "교체 시기를 메모해두기"],
    disposalType: "일반쓰레기",
    disposalGuide: "사용한 필터는 일반쓰레기로 버려주세요.",
  },
  {
    name: "수세미",
    category: "주방",
    cycle: "2~4주",
    days: 21,
    reason: "주방 수세미는 물기와 음식물이 남아 세균이 쉽게 번식할 수 있어요.",
    replaceSigns: ["냄새가 날 때", "표면이 닳았을 때", "거품이 잘 안 날 때"],
    tips: ["사용 후 충분히 말리기", "주기적으로 소독하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "오염된 합성수지 재질이라 일반쓰레기로 버려주세요.",
  },
  {
    name: "행주",
    category: "주방",
    cycle: "1~2주",
    days: 10,
    reason: "행주는 자주 젖어 있어 냄새와 오염이 쉽게 생겨요.",
    replaceSigns: ["냄새가 날 때", "얼룩이 잘 지워지지 않을 때", "섬유가 거칠어졌을 때"],
    tips: ["사용 후 바로 건조하기", "삶거나 소독해 관리하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "오염된 천 재질은 일반쓰레기로 버려주세요.",
  },
  {
    name: "고무장갑",
    category: "주방",
    cycle: "1~2개월",
    days: 45,
    reason: "찢어지거나 탄력이 줄면 보호 기능이 떨어져요.",
    replaceSigns: ["찢어졌을 때", "냄새가 심할 때", "탄력이 줄었을 때"],
    tips: ["사용 후 안팎을 건조하기", "직사광선을 피해서 보관하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "고무 재질은 대부분 일반쓰레기로 버려주세요.",
  },
  {
    name: "도마",
    category: "주방",
    cycle: "6개월~1년",
    days: 270,
    reason: "칼집이 많아지면 세균이 남기 쉬워 위생 관리가 어려워질 수 있어요.",
    replaceSigns: ["깊은 칼집이 많을 때", "냄새가 배었을 때", "표면 변형이 심할 때"],
    tips: ["용도별로 구분 사용하기", "세척 후 완전히 건조하기"],
    disposalType: "재질별 상이",
    disposalGuide: "플라스틱과 나무 모두 보통 일반쓰레기로 버리는 경우가 많아요.",
  },
  {
    name: "주방세제",
    category: "주방",
    cycle: "개봉 후 6~12개월",
    days: 270,
    reason: "오래되면 내용물 상태가 변할 수 있어요.",
    replaceSigns: ["점도가 달라졌을 때", "냄새가 달라졌을 때", "유통기한이 지났을 때"],
    tips: ["직사광선 피하기", "입구 주변 찌꺼기 닦기"],
    disposalType: "재질별 상이",
    disposalGuide: "내용물을 비운 뒤 용기 재질에 따라 분리배출 여부를 확인해 주세요.",
  },
  {
    name: "베개",
    category: "침실",
    cycle: "1~2년",
    days: 540,
    reason: "오랜 사용으로 탄성이 줄고 오염이 쌓일 수 있어요.",
    replaceSigns: ["꺼짐이 심할 때", "목이 불편할 때", "냄새나 얼룩이 계속 남을 때"],
    tips: ["베개커버를 자주 세탁하기", "소재별 세탁법을 확인하기"],
    disposalType: "대형/일반쓰레기",
    disposalGuide: "크기와 지역 규정에 따라 종량제봉투 또는 대형폐기물 대상일 수 있어요.",
  },
  {
    name: "베개커버",
    category: "침실",
    cycle: "1주",
    days: 7,
    reason: "피부와 직접 닿아 땀과 피지가 쉽게 쌓여요.",
    replaceSigns: ["냄새가 날 때", "얼룩이 생겼을 때", "촉감이 눅눅할 때"],
    tips: ["주 1회 이상 세탁하기", "여분 커버를 준비해두기"],
    disposalType: "일반쓰레기",
    disposalGuide: "오염된 섬유류는 일반쓰레기로 버려주세요.",
  },
  {
    name: "이불",
    category: "침실",
    cycle: "계절별 세탁 / 3~5년 점검",
    days: 365,
    reason: "계절 침구는 주기적인 세탁과 상태 점검이 필요해요.",
    replaceSigns: ["냄새가 날 때", "충전재가 뭉쳤을 때", "보온성이 떨어졌을 때"],
    tips: ["계절이 바뀔 때 세탁하기", "보관 전 완전히 건조하기"],
    disposalType: "대형/일반쓰레기",
    disposalGuide: "부피가 크면 지역 규정에 따라 대형폐기물로 처리해 주세요.",
  },
  {
    name: "커튼",
    category: "침실",
    cycle: "6개월~1년 세탁 / 3~5년 점검",
    days: 365,
    reason: "먼지와 생활 오염이 쌓이기 쉬워 관리가 필요해요.",
    replaceSigns: ["변색이 심할 때", "찢어졌을 때", "세탁해도 냄새가 남을 때"],
    tips: ["계절마다 세탁하기", "먼지 쌓이지 않게 환기하기"],
    disposalType: "대형/일반쓰레기",
    disposalGuide: "부피에 따라 일반쓰레기 또는 대형폐기물 기준을 확인해 주세요.",
  },
  {
    name: "옷장 제습제",
    category: "침실",
    cycle: "1~3개월",
    days: 60,
    reason: "흡습력이 다하면 냄새와 습기 방지 효과가 줄어요.",
    replaceSigns: ["내용물이 가득 찼을 때", "습기 냄새가 날 때", "제품 권장 기간이 지났을 때"],
    tips: ["밀폐된 공간에 두기", "내용물이 차면 바로 교체하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "내용물을 처리한 뒤 용기 재질에 따라 분리배출 여부를 확인해 주세요.",
  },
  {
    name: "걸레",
    category: "청소",
    cycle: "2~4주",
    days: 21,
    reason: "반복 사용 시 오염물이 쌓여 청소 효율이 떨어질 수 있어요.",
    replaceSigns: ["냄새가 날 때", "얼룩이 남을 때", "잘 닦이지 않을 때"],
    tips: ["사용 후 세탁하고 건조하기", "용도별로 구분해서 사용하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "오염된 걸레는 일반쓰레기로 버려주세요.",
  },
  {
    name: "청소포",
    category: "청소",
    cycle: "1회 사용 또는 상태별 교체",
    days: 1,
    reason: "먼지와 오염물을 흡착한 후에는 청소 효과가 크게 떨어져요.",
    replaceSigns: ["먼지가 가득 묻었을 때", "닦임이 약해졌을 때", "찢어졌을 때"],
    tips: ["마른용·물걸레용 구분하기", "오염이 심하면 바로 교체하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "오염된 일회용 청소포는 일반쓰레기로 버려주세요.",
  },
  {
    name: "청소기 필터",
    category: "청소",
    cycle: "3~6개월",
    days: 120,
    reason: "필터가 막히면 흡입력과 차단 성능이 떨어질 수 있어요.",
    replaceSigns: ["필터 색이 심하게 변했을 때", "먼지가 잘 털리지 않을 때", "흡입력이 떨어질 때"],
    tips: ["세척 가능 여부 확인하기", "완전히 말린 뒤 재사용하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "사용한 필터는 일반쓰레기로 버려주세요.",
  },
  {
    name: "청소기 먼지봉투",
    category: "청소",
    cycle: "1~3개월",
    days: 60,
    reason: "먼지봉투가 가득 차면 흡입력이 떨어질 수 있어요.",
    replaceSigns: ["흡입력이 약해졌을 때", "봉투가 가득 찼을 때", "먼지 냄새가 날 때"],
    tips: ["권장 교체 주기 확인하기", "가득 차기 전에 교체하기"],
    disposalType: "일반쓰레기",
    disposalGuide: "먼지가 가득 찬 봉투는 일반쓰레기로 버려주세요.",
  },
  {
    name: "세탁망",
    category: "청소",
    cycle: "6개월~1년",
    days: 270,
    reason: "찢어지거나 지퍼가 망가지면 세탁 보호 기능이 떨어져요.",
    replaceSigns: ["망이 찢어졌을 때", "지퍼가 고장났을 때", "원단이 약해졌을 때"],
    tips: ["사용 후 말리기", "무거운 빨래 과하게 넣지 않기"],
    disposalType: "일반쓰레기",
    disposalGuide: "섬유와 지퍼가 섞인 제품은 일반쓰레기로 버려주세요.",
  },
];

export const consumablesByName = new Map(
  consumables.map((consumable) => [consumable.name, consumable]),
);

export const categories = [...new Set(consumables.map((consumable) => consumable.category))];
